#! /bin/sh

# Make sure to run this script not as root as the script will ask for your password when it needs it

outputsection(){
tput setaf $2; echo "$1" ; tput sgr 0
}

# asks for which config to use

outputsection "Which config do you wish to use?" 2
outputsection "1 for laptop/single monitor, 2 for desktop/multi-monitor. Default is 1" 3
#outputsection $PWD 1
read input

input="${input:=1}"


# pulls necessary repositories, first with ssh then with http
# if it fails then it will pull the repository to update it

outputsection "Pulling DWM" 2
$(git clone git@github.com:Ki11erRabbit/DWM.git || git clone https://github.com/Ki11erRabbit/DWM) || cd DWM && git pull && cd .. 
echo " "
#outputsection $PWD 1

outputsection "Pulling dwmblocks-async" 2
$(git clone git@github.com:Ki11erRabbit/dwmblocks-async.git || git clone https://github.com/Ki11erRabbit/dwmblocks-async) || cd dwmblocks-async && git pull && cd .. 
echo " "

outputsection "Pulling dmenu" 2
$(git clone git@github.com:Ki11erRabbit/dmenu.git || git clone https://github.com/Ki11erRabbit/dmenu) || cd dmenu && git pull && cd ..
echo " "

input="${input:=1}"


# installs DWM 
outputsection "Installing DWM enter your password" 2
cd DWM

case $input in
	1) outputsection "Adjusting dwm.c" 2 
		sed 's/\/\*- getsystraywidth()\*\//- getsystraywidth()/' dwm.c > dwm.c;;
esac

sudo make install
cd ..
echo " "
#outputsection $PWD 1

#moves scripts for dwm and dwmblocks
outputsection "Moving scripts for dwmblocks and other scripts" 2
cp -rf .dwm ~/
cp -rf scripts/bin/ ~/.local/
echo " "
#outputsection $PWD 1

#installs dwmblocks-async
outputsection "Installing dwmblocks-async" 2
cd dwmblocks-async

case $input in
	2) outputsection "Adjusting blocks config" 2 
		sed 's/BLOCK(\"~\/.dwm\/blocks-scripts\/battery\"/\/\/BLOCK(\"~\/.dwm\/blocks-scripts\/battery\"/' config.h > config.h;;
esac

sudo make install
cd ..
echo " "
#outputsection $PWD 1

outputsection "Installing dmenu" 2
cd dmenu
sudo make install
cd ..
echo " "
#outputsection $PWD 1

desktop() {
cp -rf dot-files/desktop/. ~/
}

laptop() {
cp -rfv dot-files/laptop/. ~/
}


case $input in
	1) laptop ;;
	2) desktop ;;
esac
echo " "

#outputsection $PWD 1
outputsection "Installing remaining config files" 2
cp -rfv dot-files/general/. ~/

outputsection "Installing libxft-bgra if it doesn't exist" 2
yay -Q libxft-bgra || yay -S libxft-bgra
echo " "


outputsection "Installing remaing required software" 2
yay -S alacrity copyq flameshot cmus pamixer pulsemixer handlr picom zsh
echo " "

outputsection "Installing laptop or desktop software" 2
outputsection "1 for desktop, 2 for laptop. Default is 1" 3
#outputsection $PWD 1
read input2

input="${input2:=1}"

case $input in
	1) yay -S gddcontrol ;;
	2) yay -S touchegg touche light tlp acpi ;;
esac
echo " "

outputsection "Installing deadd-notification-center. May take awhile" 1
yay -S dead-notification-center-git 

