#! /bin/sh

# Make sure to run this script not as root as the script will ask for your password when it needs it

outputsection(){
tput setaf $2; echo "$1" ; tput sgr 0
}


# pulls necessary repositories, first with ssh then with http
# if it fails then it will pull the repository to update it

outputsection "Pulling DWM" 2
$(git clone git@github.com:Ki11erRabbit/DWM.git || git clone https://github.com/Ki11erRabbit/DWM) || cd DWM && git pull && cd .. 
echo " "
#outputsection $PWD 1

outputsection "Pulling dwmblocks-async" 2
$(git clone git@github.com:Ki11erRabbit/dwmblocks-async.git || git clone https://github.com/Ki11erRabbit/dwmblocks-async) || cd dwmblocks-async && git pull && cd .. 
echo " "

outputsection "Pulling dmenu" 2
$(git clone git@github.com:Ki11erRabbit/dmenu.git || git clone https://github.com/Ki11erRabbit/dmenu) || cd dmenu && git pull && cd ..
echo " "

# installs DWM 
outputsection "Installing DWM enter your password" 2
cd DWM
sudo make install
cd ..
echo " "
#outputsection $PWD 1

#moves scripts for dwm and dwmblocks
outputsection "Moving scripts for dwmblocks and other scripts" 2
cp -rf .dwm ~/
cp -rf scripts/bin/ ~/.local/
echo " "
#outputsection $PWD 1

#installs dwmblocks-async
outputsection "Installing dwmblocks-async" 2
cd dwmblocks-async
sudo make install
cd ..
echo " "
#outputsection $PWD 1

outputsection "Installing dmenu" 2
cd dmenu
sudo make install
cd ..
echo " "
#outputsection $PWD 1

desktop() {
cp -rf dot-files/desktop/* ~/
}

laptop() {
cp -rfv dot-files/laptop/* ~/
}

# asks for which config to use

outputsection "Which config do you wish to use?" 2
outputsection "1 for laptop/single monitor, 2 for desktop/multi-monitor. Default is 1" 3
#outputsection $PWD 1
read input

input=${1:-$input}

case $input in
	1) laptop ;;
	2) desktop ;;
esac
echo " "

outputsection "Installing remaining config files" 2
cp -rfv dot-files/general/* ~/

