#! /bin/sh

# Make sure to run this script not as root as the script will ask for your password when it needs it

# pulls necessary repositories, first with ssh then with http
# if it fails then it will pull the repository to update it

tput setaf 2; echo "Pulling DWM" ; tput sgr 0
$(git clone git@github.com:Ki11erRabbit/DWM.git || git clone https://github.com/Ki11erRabbit/DWM) || cd DWM && git pull && cd .. 
echo " "

tput setaf 2; echo "Pulling dwmblocks-async" ; tput sgr 0
$(git clone git@github.com:Ki11erRabbit/dwmblocks-async.git || git clone https://github.com/Ki11erRabbit/dwmblocks-async) || cd dwmblocks-async && git pull && cd .. 
echo " "

# installs DWM 
tput setaf 2; echo "Installing DWM enter your password" ; tput sgr 0
cd DWM
sudo make install
cd ..
echo " "

#moves scripts for dwm and dwmblocks
tput setaf 2; echo "Moving scripts for dwmblocks and other scripts" ; tput sgr 0
cp -rf .dwm ~/
cp -rf scripts/bin/ ~/.local/
echo " "

#installs dwmblocks-async
tput setaf 2; echo "Installing dwmblocks-async" ; tput sgr 0
cd dwmblocks-async
sudo make install
echo " "
